//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string idAgent { get; set; }
        public string Agent { get; set; }
        public string idKontr { get; set; }
        public string Kontr { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public decimal DCredit { get; set; }
        public decimal Credit { get; set; }
        public decimal TCredit { get; set; }
        public string dep { get; set; }
        public int ToPay { get; set; }
    }
}
