//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class balDoc
    {
        public int id { get; set; }
        public System.DateTime period { get; set; }
        public string agent { get; set; }
        public string customer { get; set; }
        public string docno { get; set; }
        public decimal balBeg { get; set; }
        public decimal shippment { get; set; }
        public decimal payment { get; set; }
        public decimal balEnd { get; set; }
    }
}
