//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoCustomer
    {
        public int id { get; set; }
        public string idAgent { get; set; }
        public string idKontr { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public System.DateTime timeStamp { get; set; }
    }
}
