//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int id { get; set; }
        public string agent { get; set; }
        public string ware { get; set; }
        public decimal select { get; set; }
        public decimal planTT { get; set; }
        public decimal planSale { get; set; }
        public decimal planQuant { get; set; }
        public decimal planWeight { get; set; }
        public decimal rate { get; set; }
        public decimal selectQuant { get; set; }
        public decimal percExec { get; set; }
        public decimal sale { get; set; }
        public decimal quant { get; set; }
        public int tp { get; set; }
    }
}
